### ISSUE TITLE
dfn_skype not showing up in OPSI repository

### ISSUE THREAD

**Issue by ateuber** [opsi4instituts/dfn_skype#1]
So far we updated Skype using https://opsi.wzb.eu/. It is not listed there any more, but still updated here at Github. Is there a reason for this or is it an error? Thanks!

**Comment by wzb-opsi** [comment]
Dear Andreas,

that package was put in accidentally in the public space. I put it back 
to non-public. If you are a member of the DFN we can provide you with 
credentials to log in and get the package. We are not entitled to offer 
proprietary software from our servers to the public. :(

Best regards from the WZB,

Eric


Am 30.10.2018 um 12:21 schrieb Andreas Teuber:
> So far we updated Skype using https://opsi.wzb.eu/. It is not listed there any more, but still updated here at Github. Is there a reason for this or is it an error? Thanks!
> 

-- 
======================================================

Eric Esser
DV-Koordination / IT Department
Betriebsratsmitglied / Member of Works Council
Wissenschaftszentrum Berlin für Sozialforschung gGmbH

Reichpietschufer 50
10785 Berlin
Germany

Fon : +49-30-25491-560/585
Fax : +49-30-25491-558
Mail: eric.esser@wzb.eu

Service:
Di/Tue  9:00-17:30
Mi/Wed  9:30-17:30
Do/Thu  9:30-17:30

Ich bin gegen die Einführung des Internet,
weil es nur noch mehr Menschen erlaubt zusammenzukommen,
um zusammen dumm zu sein.
(Gustave Flaubert)
======================================================

**Comment by ateuber** [comment]
I see, thanks anyway for your fast reply then.
